### ISSUE TITLE
Import database UI unclear

### ISSUE THREAD

**Issue by galgalesh** [DannyGB/KeePassTouch#22]
1. import database
2. choose file manager
3. choose file

Now I'm on the 'importing database' screen. This screen confuses me.

![screenshot20160721_003002249](https://cloud.githubusercontent.com/assets/1492981/17005447/913ebe4c-4eda-11e6-95f4-ffcb7986fb2b.png)

Is importing happening, or did it succeed? Clicking on the database does nothing. Going back does nothing (at first). After a while I reopen the app and the database is visible in "available databases".

Possible solutions
- Don't show this screen, go directly to 'available databases' when database is imported
- Show loader if importing is in progress
- Show big button "import succeeded, go to available databases"

**Comment by DannyGB** [comment]
Altered in the next release to not show the imported screen and instead to return the user back to the "Available..." screen
