### ISSUE TITLE
Database text very small om Meizu PRO5

### ISSUE THREAD

**Issue by galgalesh** [DannyGB/KeePassTouch#23]
Text is very small on the 'available databases' screen and on the screen that shows the content of your database.

![screenshot20160721_003010239](https://cloud.githubusercontent.com/assets/1492981/17005559/42e72c9c-4edb-11e6-9167-ea61a9edbf0d.png)

This is not the case in the "importing database" screen. Seems you should just do what you did there.. :)

![screenshot20160721_003002249](https://cloud.githubusercontent.com/assets/1492981/17005598/73c28104-4edb-11e6-8618-59228f4117ed.png)

PS: Big thanks for this app! Is there a blog somewhere about how this app was created? I'm interested to know how it works under the hood, what libraries you used etc..

**Comment by DannyGB** [comment]
Hi galgalesh,

Thanks for your feedback, I'll take on board what you're saying :)

There is currently no blog for this application but I could perhaps add something to the Wiki regarding the process I went through to get to where I am etc...

As a side note and as you mentioned the Meizu PRO5; my BQ was broken a couple of months back and I was hoping to replace it with a PRO5 but I am struggling to find one, maybe you know where I might find one in-stock (all mobile devices seem to be out-of-stock, only the BQ10 tablet is available)!?

Anyway, thanks for the feedback

db

PS. I went to Ghent once it was an amazing place

**Comment by galgalesh** [comment]
Not sure where you can get one. I've followed the page closely for a few weeks and at a certain point I got lucky and was fast enough to order one...

**Comment by DannyGB** [comment]
Fixed in next release
