### ISSUE TITLE
[Discussion] Continuing development

### ISSUE THREAD

**Issue by Talkless** [DannyGB/KeePassTouch#29]
Hi,

I have created UBPorts forum post about possibility to organize a phone for app maintainer:
https://forums.ubports.com/topic/1013/consider-donating-phone-for-keepit-keepasstouch-developer

The first question is, would you @DannyGB would consider continuing work if Ubuntu Touch device was available for you?

For me, personally, this app is really one of "must haves", a really important item in Ubuntu Touch app ecosystem.

**Comment by DannyGB** [comment]
Hi Talkless,

I've responded to your post over on UBPorts

**Comment by wilfridd** [comment]
Hi DannyGB,
I'd like to submit some minor changes (component update, bigger text size, etc), but I'm a complete noob with GH and I don’t know how to push the whole thing back to GH to make it available for review...
I'm using QT Creator. I've cloned the master branch locally, did my changes and successfully compiled and created a new click package.

**Comment by DannyGB** [comment]
Hi,

The process usually goes like this:

* fork my repo
* clone the fork locally
* Make your changes
* Commit changes to your local repo
* Push your changes back to your GH fork
* Submit a pull request
* I review the pull request and commit the changes into my repo.

I notice I've a couple of pull requests already so maybe you've already submitted one. I'm take a look.

**Comment by wilfridd** [comment]
Hi,
It's done.
Once you commit changes to your repo, next step is to publish the click package on UT openstore ?

**Comment by wilfridd** [comment]
Btw, I've installed the new click package (v2.0.2) on UT Xenial...works pretty well.
Small issue with the "import database from" screen : there's not icon for the File Manager that allows to browse for a DBfile to import. It show only icon for Browser

**Comment by DannyGB** [comment]
Releasing a new click package onto the OpenStore is usually done when either:

1. I finish all of the changes that I want to release in the "next" version or
2. Critical bug fix(es) are made that can't wait until the next release or
3. I feel a feature deserves to be released out of cycle (maybe it's a useful feature and the next release is a long way off) but this is usually an exception and is unlikely to be a major update as I don't want the app to become unstable

**Comment by j2g2rp** [comment]
Hi Danny.
I'm trying to open a data base wich have a key to open it. I saved the same kdbx with an xml 1.0 key and with an AES-KDF (KDBX3.1) with KeepassXc.
When i try to open it I recieve in both cases errors with the key.

Wich are the requirements to open them with keepit?
Thanks in advance.

**Comment by Talkless** [comment]
@j2g2rp could you consider creating issue for supporting keys?

I'm closing this issue because we just got new release, proving that development is continuing! Thanks!
