### ISSUE TITLE
Some .key files returns error when trying to open a database

### ISSUE THREAD

**Issue by j2g2rp** [DannyGB/KeePassTouch#32]
Looks like some kdbx databases wich are protected with a .key file can't be openned ("invalid composite key")

I tried to open it with a xml 1.0 .key file and with a AES-KDF (KDBX 3.1). 
For more information I'm using in my laptop KeepassXC without any problems.

If i can test something to track the problem just let me know.
Thanks for your  efforts.

**Comment by DannyGB** [comment]
Hi,

I cannot replicate this issue.

If you are able to replicate it with a new database containing dummy data please send me the dummy database and I'll look into this further?

db

**Comment by j2g2rp** [comment]
Sure.
I've sent it to  your email rightnow.
The password is: prueba

Let me know if I can do something else.

**Comment by DannyGB** [comment]
Apologies for the significant delay in this response.
With KeePit version 3.1 I was able to successfully open the database that you sent through

![screenshot20190713_211311532](https://user-images.githubusercontent.com/724238/61176115-13b70000-a5b3-11e9-842e-95aa4faf797f.png)
