### ISSUE TITLE
Release version for 16.04

### ISSUE THREAD

**Issue by Talkless** [DannyGB/KeePassTouch#33]
[Ubuntu Touch RC OTA-4 is availabe](https://ubports.com/blog/ubports-blog-1/post/ubuntu-touch-rc-ota-4-148), and if I understood correctly, non-qml-only apps must be rebuilt for 16.04, meanwhile QML apps will "just work". It would be nice to have Keepit for 16.04 on it's release date (or not too much later).

**Comment by DannyGB** [comment]
This is on my radar. 

Firstly I need to update my device as I'm still on 15.04 (r3). Once I've done that I'll start looking at the re-compile/test cycle for the 16.04 build.

Once I'm satisfied that there are no regression issues with KeepIt and Xenial I'll upload a new package to the AppStore

**Comment by Talkless** [comment]
Thanks @DannyGB , good to know.

**Comment by advocatux** [comment]
Any update about this issue? OTA-4 is pretty close now :)

Thank you for your work !!

**Comment by DannyGB** [comment]
I have a successful build, just need to package it up and get it uploaded to the store

**Comment by advocatux** [comment]
If you want some kind of testing before uploading your app to the store, the OpenStore group in Telegram (https://open-store.io/telegram) is the usual place to do it.

Thanks again for your work !!

**Comment by Talkless** [comment]
Thanks @DannyGB ! I have not yet upgraded system, so no comments yet.
