### ISSUE TITLE
Graphic Problems

### ISSUE THREAD

**Issue by theBest3000** [DannyGB/KeePassTouch#34]
Switching to landscape on BQ Aquaris E4.5 leads to Buttons in the titlebar. (02 of images) Switching back to portrait hides the "Show password" toggle. (03 of images) On first startup everything is fine. (02 of images)

In portrait on BQ Aquaris M10 HD no "Show password" toggle is visible. (01 of images) In landscape everything is fine. (02 of images)

![bqaquarise4 5_01](https://user-images.githubusercontent.com/44313069/47253384-fc971780-d451-11e8-9c3c-0dc3184a7d2c.png)
![bqaquarise4 5_02](https://user-images.githubusercontent.com/44313069/47253385-00c33500-d452-11e8-9bfc-50cb184d5530.png)
![bqaquarise4 5_03](https://user-images.githubusercontent.com/44313069/47253386-03258f00-d452-11e8-8be0-18206ade3601.png)
![bqaquarism10hd_01](https://user-images.githubusercontent.com/44313069/47253389-06207f80-d452-11e8-9216-2f63b7a57a79.png)
![bqaquarism10hd_02](https://user-images.githubusercontent.com/44313069/47253390-0882d980-d452-11e8-9cb7-d608b4f59ddd.png)

**Comment by DannyGB** [comment]
Fixed in future version
