### ISSUE TITLE
Some character in password does lead to error

### ISSUE THREAD

**Issue by theBest3000** [DannyGB/KeePassTouch#36]
Databases containing at least the character "€" can't be open by the application. See included testdatabase. The password is "ubports€a". 
[testdatabase.zip](https://github.com/DannyGB/KeePassTouch/files/2498014/testdatabase.zip)

Not sure about other characters.

**Comment by DannyGB** [comment]
Duplicate of #18, I'm going to move the test DB you supplied over to that issue
